//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.Database
{
    using pide_api.Utils;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PideDatabase : DbContext
    {
        public PideDatabase()
            : base("name=PideDatabase")
        {
        }

        public PideDatabase(string connectionString) 
            : base(connectionString){
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {    
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLPIDE_CONSULTA> TBLPIDE_CONSULTA { get; set; }
        public virtual DbSet<TBLPIDE_CONSULTA_LOG> TBLPIDE_CONSULTA_LOG { get; set; }
        public virtual DbSet<TBLPIDE_TOKEN> TBLPIDE_TOKEN { get; set; }
    }
}
