//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPIDE_CONSULTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPIDE_CONSULTA()
        {
            this.TBLPIDE_CONSULTA_LOG = new HashSet<TBLPIDE_CONSULTA_LOG>();
        }
    
        public byte CCONS_CONSULTA_ID { get; set; }
        public string SCONS_NOMBRE { get; set; }
        public string SCONS_DETALLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPIDE_CONSULTA_LOG> TBLPIDE_CONSULTA_LOG { get; set; }
    }
}
