//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPIDE_CONSULTA_LOG
    {
        public int CCONSLOG_CONSULTA_LOG_ID { get; set; }
        public string SCONSLOG_USUARIO { get; set; }
        public System.DateTime DCONSLOG_FECHA_HORA { get; set; }
        public string SCONSLOG_PARAMETROS_REQUEST { get; set; }
        public string CCCONSLOG_ERROR { get; set; }
        public string SCONSLOG_COMENTARIO_ERROR { get; set; }
        public byte CCONS_CONSULTA_ID { get; set; }
    
        public virtual TBLPIDE_CONSULTA TBLPIDE_CONSULTA { get; set; }
    }
}
