//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPIDE_TOKEN
    {
        public decimal CTOK_TOKEN_ID { get; set; }
        public string STOK_USUARIO_ID { get; set; }
        public string STOK_AUTH_TOKEN { get; set; }
        public Nullable<System.DateTime> DTOK_FECHA_EXPIRACION { get; set; }
        public Nullable<System.DateTime> DTOK_FECHA_CREACION { get; set; }
    }
}
