//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.Pruebawebserv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.reniec.gob.pe/", ConfigurationName="Pruebawebserv.ReniecConsultaDniPortType")]
    public interface ReniecConsultaDniPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="consultar", ReplyAction="http://ws.reniec.gob.pe/ConsultaPide/consultarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        pide_api.Pruebawebserv.consultarResponse consultar(pide_api.Pruebawebserv.consultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultar", ReplyAction="http://ws.reniec.gob.pe/ConsultaPide/consultarResponse")]
        System.Threading.Tasks.Task<pide_api.Pruebawebserv.consultarResponse> consultarAsync(pide_api.Pruebawebserv.consultarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="actualizarcredencial", ReplyAction="http://ws.reniec.gob.pe/ConsultaPide/actualizarcredencialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        pide_api.Pruebawebserv.actualizarcredencialResponse actualizarcredencial(pide_api.Pruebawebserv.actualizarcredencialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="actualizarcredencial", ReplyAction="http://ws.reniec.gob.pe/ConsultaPide/actualizarcredencialResponse")]
        System.Threading.Tasks.Task<pide_api.Pruebawebserv.actualizarcredencialResponse> actualizarcredencialAsync(pide_api.Pruebawebserv.actualizarcredencialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.reniec.gob.pe/")]
    public partial class peticionConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nuDniConsultaField;
        
        private string nuDniUsuarioField;
        
        private string nuRucUsuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nuDniConsulta {
            get {
                return this.nuDniConsultaField;
            }
            set {
                this.nuDniConsultaField = value;
                this.RaisePropertyChanged("nuDniConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nuDniUsuario {
            get {
                return this.nuDniUsuarioField;
            }
            set {
                this.nuDniUsuarioField = value;
                this.RaisePropertyChanged("nuDniUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nuRucUsuario {
            get {
                return this.nuRucUsuarioField;
            }
            set {
                this.nuRucUsuarioField = value;
                this.RaisePropertyChanged("nuRucUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.reniec.gob.pe/")]
    public partial class resultadoActualizacionCredencial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coResultadoField;
        
        private string deResultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string coResultado {
            get {
                return this.coResultadoField;
            }
            set {
                this.coResultadoField = value;
                this.RaisePropertyChanged("coResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deResultado {
            get {
                return this.deResultadoField;
            }
            set {
                this.deResultadoField = value;
                this.RaisePropertyChanged("deResultado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.reniec.gob.pe/")]
    public partial class peticionActualizarCredencial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string credencialAnteriorField;
        
        private string credencialNuevaField;
        
        private string nuDniField;
        
        private string nuRucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string credencialAnterior {
            get {
                return this.credencialAnteriorField;
            }
            set {
                this.credencialAnteriorField = value;
                this.RaisePropertyChanged("credencialAnterior");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string credencialNueva {
            get {
                return this.credencialNuevaField;
            }
            set {
                this.credencialNuevaField = value;
                this.RaisePropertyChanged("credencialNueva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nuDni {
            get {
                return this.nuDniField;
            }
            set {
                this.nuDniField = value;
                this.RaisePropertyChanged("nuDni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nuRuc {
            get {
                return this.nuRucField;
            }
            set {
                this.nuRucField = value;
                this.RaisePropertyChanged("nuRuc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.reniec.gob.pe/")]
    public partial class datosPersona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apPrimerField;
        
        private string apSegundoField;
        
        private string direccionField;
        
        private string estadoCivilField;
        
        private byte[] fotoField;
        
        private string prenombresField;
        
        private string restriccionField;
        
        private string ubigeoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apPrimer {
            get {
                return this.apPrimerField;
            }
            set {
                this.apPrimerField = value;
                this.RaisePropertyChanged("apPrimer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apSegundo {
            get {
                return this.apSegundoField;
            }
            set {
                this.apSegundoField = value;
                this.RaisePropertyChanged("apSegundo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string prenombres {
            get {
                return this.prenombresField;
            }
            set {
                this.prenombresField = value;
                this.RaisePropertyChanged("prenombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string restriccion {
            get {
                return this.restriccionField;
            }
            set {
                this.restriccionField = value;
                this.RaisePropertyChanged("restriccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                this.ubigeoField = value;
                this.RaisePropertyChanged("ubigeo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.reniec.gob.pe/")]
    public partial class resultadoConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coResultadoField;
        
        private datosPersona datosPersonaField;
        
        private string deResultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string coResultado {
            get {
                return this.coResultadoField;
            }
            set {
                this.coResultadoField = value;
                this.RaisePropertyChanged("coResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public datosPersona datosPersona {
            get {
                return this.datosPersonaField;
            }
            set {
                this.datosPersonaField = value;
                this.RaisePropertyChanged("datosPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deResultado {
            get {
                return this.deResultadoField;
            }
            set {
                this.deResultadoField = value;
                this.RaisePropertyChanged("deResultado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://ws.reniec.gob.pe/", IsWrapped=true)]
    public partial class consultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.reniec.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public pide_api.Pruebawebserv.peticionConsulta arg0;
        
        public consultarRequest() {
        }
        
        public consultarRequest(pide_api.Pruebawebserv.peticionConsulta arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://ws.reniec.gob.pe/", IsWrapped=true)]
    public partial class consultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.reniec.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public pide_api.Pruebawebserv.resultadoConsulta @return;
        
        public consultarResponse() {
        }
        
        public consultarResponse(pide_api.Pruebawebserv.resultadoConsulta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarcredencial", WrapperNamespace="http://ws.reniec.gob.pe/", IsWrapped=true)]
    public partial class actualizarcredencialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.reniec.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public pide_api.Pruebawebserv.peticionActualizarCredencial arg0;
        
        public actualizarcredencialRequest() {
        }
        
        public actualizarcredencialRequest(pide_api.Pruebawebserv.peticionActualizarCredencial arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarcredencialResponse", WrapperNamespace="http://ws.reniec.gob.pe/", IsWrapped=true)]
    public partial class actualizarcredencialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.reniec.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public pide_api.Pruebawebserv.resultadoActualizacionCredencial @return;
        
        public actualizarcredencialResponse() {
        }
        
        public actualizarcredencialResponse(pide_api.Pruebawebserv.resultadoActualizacionCredencial @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReniecConsultaDniPortTypeChannel : pide_api.Pruebawebserv.ReniecConsultaDniPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReniecConsultaDniPortTypeClient : System.ServiceModel.ClientBase<pide_api.Pruebawebserv.ReniecConsultaDniPortType>, pide_api.Pruebawebserv.ReniecConsultaDniPortType {
        
        public ReniecConsultaDniPortTypeClient() {
        }
        
        public ReniecConsultaDniPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReniecConsultaDniPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecConsultaDniPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecConsultaDniPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.Pruebawebserv.consultarResponse pide_api.Pruebawebserv.ReniecConsultaDniPortType.consultar(pide_api.Pruebawebserv.consultarRequest request) {
            return base.Channel.consultar(request);
        }
        
        public pide_api.Pruebawebserv.resultadoConsulta consultar(pide_api.Pruebawebserv.peticionConsulta arg0) {
            pide_api.Pruebawebserv.consultarRequest inValue = new pide_api.Pruebawebserv.consultarRequest();
            inValue.arg0 = arg0;
            pide_api.Pruebawebserv.consultarResponse retVal = ((pide_api.Pruebawebserv.ReniecConsultaDniPortType)(this)).consultar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.Pruebawebserv.consultarResponse> pide_api.Pruebawebserv.ReniecConsultaDniPortType.consultarAsync(pide_api.Pruebawebserv.consultarRequest request) {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.Pruebawebserv.consultarResponse> consultarAsync(pide_api.Pruebawebserv.peticionConsulta arg0) {
            pide_api.Pruebawebserv.consultarRequest inValue = new pide_api.Pruebawebserv.consultarRequest();
            inValue.arg0 = arg0;
            return ((pide_api.Pruebawebserv.ReniecConsultaDniPortType)(this)).consultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.Pruebawebserv.actualizarcredencialResponse pide_api.Pruebawebserv.ReniecConsultaDniPortType.actualizarcredencial(pide_api.Pruebawebserv.actualizarcredencialRequest request) {
            return base.Channel.actualizarcredencial(request);
        }
        
        public pide_api.Pruebawebserv.resultadoActualizacionCredencial actualizarcredencial(pide_api.Pruebawebserv.peticionActualizarCredencial arg0) {
            pide_api.Pruebawebserv.actualizarcredencialRequest inValue = new pide_api.Pruebawebserv.actualizarcredencialRequest();
            inValue.arg0 = arg0;
            pide_api.Pruebawebserv.actualizarcredencialResponse retVal = ((pide_api.Pruebawebserv.ReniecConsultaDniPortType)(this)).actualizarcredencial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.Pruebawebserv.actualizarcredencialResponse> pide_api.Pruebawebserv.ReniecConsultaDniPortType.actualizarcredencialAsync(pide_api.Pruebawebserv.actualizarcredencialRequest request) {
            return base.Channel.actualizarcredencialAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.Pruebawebserv.actualizarcredencialResponse> actualizarcredencialAsync(pide_api.Pruebawebserv.peticionActualizarCredencial arg0) {
            pide_api.Pruebawebserv.actualizarcredencialRequest inValue = new pide_api.Pruebawebserv.actualizarcredencialRequest();
            inValue.arg0 = arg0;
            return ((pide_api.Pruebawebserv.ReniecConsultaDniPortType)(this)).actualizarcredencialAsync(inValue);
        }
    }
}
