//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pide_api.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller.pide.sunarp.gob.pe/", ConfigurationName="ServiceReference.PIDEWSService")]
    public interface PIDEWSService {
        
        // CODEGEN: Parameter 'respuestaTitularidad' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuestaTitularidad")]
        pide_api.ServiceReference.buscarTitularidadResponse buscarTitularidad(pide_api.ServiceReference.buscarTitularidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadResponse")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarTitularidadResponse> buscarTitularidadAsync(pide_api.ServiceReference.buscarTitularidadRequest request);
        
        // CODEGEN: Parameter 'respuestaNaveAeronave' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarNaveAeronaveRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarNaveAeronaveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuestaNaveAeronave")]
        pide_api.ServiceReference.buscarNaveAeronaveResponse buscarNaveAeronave(pide_api.ServiceReference.buscarNaveAeronaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarNaveAeronaveRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarNaveAeronaveResponse")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarNaveAeronaveResponse> buscarNaveAeronaveAsync(pide_api.ServiceReference.buscarNaveAeronaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="asientos")]
        pide_api.ServiceReference.respuestaPartidaBean listarAsientos(string zona, string oficina, string partida, string registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="asientos")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.respuestaPartidaBean> listarAsientosAsync(string zona, string oficina, string partida, string registro);
        
        // CODEGEN: Parameter 'img' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="img")]
        pide_api.ServiceReference.verAsientoResponse verAsiento(pide_api.ServiceReference.verAsientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoResponse")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.verAsientoResponse> verAsientoAsync(pide_api.ServiceReference.verAsientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vehiculo")]
        pide_api.ServiceReference.respuestaVehiculoBean verDetalleRPV(string zona, string oficina, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vehiculo")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.respuestaVehiculoBean> verDetalleRPVAsync(string zona, string oficina, string placa);
        
        // CODEGEN: Generating message contract since message buscarPJRazonSocialResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarPJRazonSocialRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarPJRazonSocialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pide_api.ServiceReference.buscarPJRazonSocialResponse buscarPJRazonSocial(pide_api.ServiceReference.buscarPJRazonSocialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarPJRazonSocialRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarPJRazonSocialResponse")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarPJRazonSocialResponse> buscarPJRazonSocialAsync(pide_api.ServiceReference.buscarPJRazonSocialRequest request);
        
        // CODEGEN: Generating message contract since message getOficinasResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/getOficinasRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/getOficinasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pide_api.ServiceReference.getOficinasResponse getOficinas(pide_api.ServiceReference.getOficinasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.pide.sunarp.gob.pe/PIDEWSService/getOficinasRequest", ReplyAction="http://controller.pide.sunarp.gob.pe/PIDEWSService/getOficinasResponse")]
        System.Threading.Tasks.Task<pide_api.ServiceReference.getOficinasResponse> getOficinasAsync(pide_api.ServiceReference.getOficinasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class resultadoTitularidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string registroField;
        
        private string libroField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string nombreField;
        
        private string razonSocialField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string numeroPartidaField;
        
        private string numeroPlacaField;
        
        private string estadoField;
        
        private string zonaField;
        
        private string oficinaField;
        
        private string mensajeField;
        
        private string direccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string registro {
            get {
                return this.registroField;
            }
            set {
                this.registroField = value;
                this.RaisePropertyChanged("registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string libro {
            get {
                return this.libroField;
            }
            set {
                this.libroField = value;
                this.RaisePropertyChanged("libro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroPartida {
            get {
                return this.numeroPartidaField;
            }
            set {
                this.numeroPartidaField = value;
                this.RaisePropertyChanged("numeroPartida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string numeroPlaca {
            get {
                return this.numeroPlacaField;
            }
            set {
                this.numeroPlacaField = value;
                this.RaisePropertyChanged("numeroPlaca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class oficinaRegistralBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codZonaField;
        
        private string codOficinaField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codZona {
            get {
                return this.codZonaField;
            }
            set {
                this.codZonaField = value;
                this.RaisePropertyChanged("codZona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codOficina {
            get {
                return this.codOficinaField;
            }
            set {
                this.codOficinaField = value;
                this.RaisePropertyChanged("codOficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class datosPJBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zonaField;
        
        private string oficinaField;
        
        private string partidaField;
        
        private string fichaField;
        
        private string tomoField;
        
        private string folioField;
        
        private string tipoField;
        
        private string denominacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
                this.RaisePropertyChanged("partida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ficha {
            get {
                return this.fichaField;
            }
            set {
                this.fichaField = value;
                this.RaisePropertyChanged("ficha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tomo {
            get {
                return this.tomoField;
            }
            set {
                this.tomoField = value;
                this.RaisePropertyChanged("tomo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string denominacion {
            get {
                return this.denominacionField;
            }
            set {
                this.denominacionField = value;
                this.RaisePropertyChanged("denominacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class respuestaVehiculoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string placaField;
        
        private string serieField;
        
        private string vinField;
        
        private string nro_motorField;
        
        private string colorField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string estadoField;
        
        private string sedeField;
        
        private string[] propietariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nro_motor {
            get {
                return this.nro_motorField;
            }
            set {
                this.nro_motorField = value;
                this.RaisePropertyChanged("nro_motor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("nombre", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] propietarios {
            get {
                return this.propietariosField;
            }
            set {
                this.propietariosField = value;
                this.RaisePropertyChanged("propietarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class tomoFolioBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idImgFolioField;
        
        private bool idImgFolioFieldSpecified;
        
        private string nroPagRefField;
        
        private string paginaField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idImgFolio {
            get {
                return this.idImgFolioField;
            }
            set {
                this.idImgFolioField = value;
                this.RaisePropertyChanged("idImgFolio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImgFolioSpecified {
            get {
                return this.idImgFolioFieldSpecified;
            }
            set {
                this.idImgFolioFieldSpecified = value;
                this.RaisePropertyChanged("idImgFolioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nroPagRef {
            get {
                return this.nroPagRefField;
            }
            set {
                this.nroPagRefField = value;
                this.RaisePropertyChanged("nroPagRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class fichaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idImgFichaField;
        
        private bool idImgFichaFieldSpecified;
        
        private decimal numPagField;
        
        private bool numPagFieldSpecified;
        
        private string tipoField;
        
        private numeroPaginasBean[] listPagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idImgFicha {
            get {
                return this.idImgFichaField;
            }
            set {
                this.idImgFichaField = value;
                this.RaisePropertyChanged("idImgFicha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImgFichaSpecified {
            get {
                return this.idImgFichaFieldSpecified;
            }
            set {
                this.idImgFichaFieldSpecified = value;
                this.RaisePropertyChanged("idImgFichaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal numPag {
            get {
                return this.numPagField;
            }
            set {
                this.numPagField = value;
                this.RaisePropertyChanged("numPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numPagSpecified {
            get {
                return this.numPagFieldSpecified;
            }
            set {
                this.numPagFieldSpecified = value;
                this.RaisePropertyChanged("numPagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listPag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public numeroPaginasBean[] listPag {
            get {
                return this.listPagField;
            }
            set {
                this.listPagField = value;
                this.RaisePropertyChanged("listPag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class numeroPaginasBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nroPagRefField;
        
        private string paginaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nroPagRef {
            get {
                return this.nroPagRefField;
            }
            set {
                this.nroPagRefField = value;
                this.RaisePropertyChanged("nroPagRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class asientosBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idImgAsientoField;
        
        private bool idImgAsientoFieldSpecified;
        
        private decimal numPagField;
        
        private bool numPagFieldSpecified;
        
        private string tipoField;
        
        private numeroPaginasBean[] listPagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idImgAsiento {
            get {
                return this.idImgAsientoField;
            }
            set {
                this.idImgAsientoField = value;
                this.RaisePropertyChanged("idImgAsiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImgAsientoSpecified {
            get {
                return this.idImgAsientoFieldSpecified;
            }
            set {
                this.idImgAsientoFieldSpecified = value;
                this.RaisePropertyChanged("idImgAsientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal numPag {
            get {
                return this.numPagField;
            }
            set {
                this.numPagField = value;
                this.RaisePropertyChanged("numPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numPagSpecified {
            get {
                return this.numPagFieldSpecified;
            }
            set {
                this.numPagFieldSpecified = value;
                this.RaisePropertyChanged("numPagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listPag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public numeroPaginasBean[] listPag {
            get {
                return this.listPagField;
            }
            set {
                this.listPagField = value;
                this.RaisePropertyChanged("listPag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class respuestaPartidaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long transaccionField;
        
        private string nroTotalPagField;
        
        private asientosBean[] listAsientosField;
        
        private fichaBean[] listFichasField;
        
        private tomoFolioBean[] listFoliosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nroTotalPag {
            get {
                return this.nroTotalPagField;
            }
            set {
                this.nroTotalPagField = value;
                this.RaisePropertyChanged("nroTotalPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listAsientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public asientosBean[] listAsientos {
            get {
                return this.listAsientosField;
            }
            set {
                this.listAsientosField = value;
                this.RaisePropertyChanged("listAsientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listFichas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public fichaBean[] listFichas {
            get {
                return this.listFichasField;
            }
            set {
                this.listFichasField = value;
                this.RaisePropertyChanged("listFichas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listFolios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tomoFolioBean[] listFolios {
            get {
                return this.listFoliosField;
            }
            set {
                this.listFoliosField = value;
                this.RaisePropertyChanged("listFolios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
    public partial class respuestaNaveAeronaveBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string matriculaField;
        
        private string oficinaField;
        
        private string numeroPartidaField;
        
        private string numeroFichaField;
        
        private string registroField;
        
        private string libroField;
        
        private string numeroSerieField;
        
        private string modeloField;
        
        private string tipoBienField;
        
        private string[] tomoFolioField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
                this.RaisePropertyChanged("matricula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string numeroPartida {
            get {
                return this.numeroPartidaField;
            }
            set {
                this.numeroPartidaField = value;
                this.RaisePropertyChanged("numeroPartida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroFicha {
            get {
                return this.numeroFichaField;
            }
            set {
                this.numeroFichaField = value;
                this.RaisePropertyChanged("numeroFicha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string registro {
            get {
                return this.registroField;
            }
            set {
                this.registroField = value;
                this.RaisePropertyChanged("registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string libro {
            get {
                return this.libroField;
            }
            set {
                this.libroField = value;
                this.RaisePropertyChanged("libro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoBien {
            get {
                return this.tipoBienField;
            }
            set {
                this.tipoBienField = value;
                this.RaisePropertyChanged("tipoBien");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tomoFolio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] tomoFolio {
            get {
                return this.tomoFolioField;
            }
            set {
                this.tomoFolioField = value;
                this.RaisePropertyChanged("tomoFolio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarTitularidad", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarTitularidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tipoParticipante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string razonSocial;
        
        public buscarTitularidadRequest() {
        }
        
        public buscarTitularidadRequest(string tipoParticipante, string apellidoPaterno, string apellidoMaterno, string nombres, string razonSocial) {
            this.tipoParticipante = tipoParticipante;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.nombres = nombres;
            this.razonSocial = razonSocial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarTitularidadResponse", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarTitularidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("respuestaTitularidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pide_api.ServiceReference.resultadoTitularidad[] respuestaTitularidad;
        
        public buscarTitularidadResponse() {
        }
        
        public buscarTitularidadResponse(pide_api.ServiceReference.resultadoTitularidad[] respuestaTitularidad) {
            this.respuestaTitularidad = respuestaTitularidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarNaveAeronave", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarNaveAeronaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string numeroMatricula;
        
        public buscarNaveAeronaveRequest() {
        }
        
        public buscarNaveAeronaveRequest(string numeroMatricula) {
            this.numeroMatricula = numeroMatricula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarNaveAeronaveResponse", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarNaveAeronaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("respuestaNaveAeronave", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pide_api.ServiceReference.respuestaNaveAeronaveBean[] respuestaNaveAeronave;
        
        public buscarNaveAeronaveResponse() {
        }
        
        public buscarNaveAeronaveResponse(pide_api.ServiceReference.respuestaNaveAeronaveBean[] respuestaNaveAeronave) {
            this.respuestaNaveAeronave = respuestaNaveAeronave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verAsiento", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class verAsientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long idImg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string nroTotalPag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string nroPagRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pagina;
        
        public verAsientoRequest() {
        }
        
        public verAsientoRequest(long transaccion, long idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            this.transaccion = transaccion;
            this.idImg = idImg;
            this.tipo = tipo;
            this.nroTotalPag = nroTotalPag;
            this.nroPagRef = nroPagRef;
            this.pagina = pagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verAsientoResponse", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class verAsientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] img;
        
        public verAsientoResponse() {
        }
        
        public verAsientoResponse(byte[] img) {
            this.img = img;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPJRazonSocial", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarPJRazonSocialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string razonSocial;
        
        public buscarPJRazonSocialRequest() {
        }
        
        public buscarPJRazonSocialRequest(string razonSocial) {
            this.razonSocial = razonSocial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPJRazonSocialResponse", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class buscarPJRazonSocialResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pide_api.ServiceReference.datosPJBean[] personaJuridica;
        
        public buscarPJRazonSocialResponse() {
        }
        
        public buscarPJRazonSocialResponse(pide_api.ServiceReference.datosPJBean[] personaJuridica) {
            this.personaJuridica = personaJuridica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOficinas", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class getOficinasRequest {
        
        public getOficinasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOficinasResponse", WrapperNamespace="http://controller.pide.sunarp.gob.pe/", IsWrapped=true)]
    public partial class getOficinasResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://controller.pide.sunarp.gob.pe/")]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("oficina", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pide_api.ServiceReference.oficinaRegistralBean[] oficina;
        
        public getOficinasResponse() {
        }
        
        public getOficinasResponse(pide_api.ServiceReference.oficinaRegistralBean[] oficina) {
            this.oficina = oficina;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PIDEWSServiceChannel : pide_api.ServiceReference.PIDEWSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIDEWSServiceClient : System.ServiceModel.ClientBase<pide_api.ServiceReference.PIDEWSService>, pide_api.ServiceReference.PIDEWSService {
        
        public PIDEWSServiceClient() {
        }
        
        public PIDEWSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIDEWSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIDEWSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIDEWSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.ServiceReference.buscarTitularidadResponse pide_api.ServiceReference.PIDEWSService.buscarTitularidad(pide_api.ServiceReference.buscarTitularidadRequest request) {
            return base.Channel.buscarTitularidad(request);
        }
        
        public pide_api.ServiceReference.resultadoTitularidad[] buscarTitularidad(string tipoParticipante, string apellidoPaterno, string apellidoMaterno, string nombres, string razonSocial) {
            pide_api.ServiceReference.buscarTitularidadRequest inValue = new pide_api.ServiceReference.buscarTitularidadRequest();
            inValue.tipoParticipante = tipoParticipante;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.nombres = nombres;
            inValue.razonSocial = razonSocial;
            pide_api.ServiceReference.buscarTitularidadResponse retVal = ((pide_api.ServiceReference.PIDEWSService)(this)).buscarTitularidad(inValue);
            return retVal.respuestaTitularidad;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarTitularidadResponse> pide_api.ServiceReference.PIDEWSService.buscarTitularidadAsync(pide_api.ServiceReference.buscarTitularidadRequest request) {
            return base.Channel.buscarTitularidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.buscarTitularidadResponse> buscarTitularidadAsync(string tipoParticipante, string apellidoPaterno, string apellidoMaterno, string nombres, string razonSocial) {
            pide_api.ServiceReference.buscarTitularidadRequest inValue = new pide_api.ServiceReference.buscarTitularidadRequest();
            inValue.tipoParticipante = tipoParticipante;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.nombres = nombres;
            inValue.razonSocial = razonSocial;
            return ((pide_api.ServiceReference.PIDEWSService)(this)).buscarTitularidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.ServiceReference.buscarNaveAeronaveResponse pide_api.ServiceReference.PIDEWSService.buscarNaveAeronave(pide_api.ServiceReference.buscarNaveAeronaveRequest request) {
            return base.Channel.buscarNaveAeronave(request);
        }
        
        public pide_api.ServiceReference.respuestaNaveAeronaveBean[] buscarNaveAeronave(string numeroMatricula) {
            pide_api.ServiceReference.buscarNaveAeronaveRequest inValue = new pide_api.ServiceReference.buscarNaveAeronaveRequest();
            inValue.numeroMatricula = numeroMatricula;
            pide_api.ServiceReference.buscarNaveAeronaveResponse retVal = ((pide_api.ServiceReference.PIDEWSService)(this)).buscarNaveAeronave(inValue);
            return retVal.respuestaNaveAeronave;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarNaveAeronaveResponse> pide_api.ServiceReference.PIDEWSService.buscarNaveAeronaveAsync(pide_api.ServiceReference.buscarNaveAeronaveRequest request) {
            return base.Channel.buscarNaveAeronaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.buscarNaveAeronaveResponse> buscarNaveAeronaveAsync(string numeroMatricula) {
            pide_api.ServiceReference.buscarNaveAeronaveRequest inValue = new pide_api.ServiceReference.buscarNaveAeronaveRequest();
            inValue.numeroMatricula = numeroMatricula;
            return ((pide_api.ServiceReference.PIDEWSService)(this)).buscarNaveAeronaveAsync(inValue);
        }
        
        public pide_api.ServiceReference.respuestaPartidaBean listarAsientos(string zona, string oficina, string partida, string registro) {
            return base.Channel.listarAsientos(zona, oficina, partida, registro);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.respuestaPartidaBean> listarAsientosAsync(string zona, string oficina, string partida, string registro) {
            return base.Channel.listarAsientosAsync(zona, oficina, partida, registro);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.ServiceReference.verAsientoResponse pide_api.ServiceReference.PIDEWSService.verAsiento(pide_api.ServiceReference.verAsientoRequest request) {
            return base.Channel.verAsiento(request);
        }
        
        public byte[] verAsiento(long transaccion, long idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            pide_api.ServiceReference.verAsientoRequest inValue = new pide_api.ServiceReference.verAsientoRequest();
            inValue.transaccion = transaccion;
            inValue.idImg = idImg;
            inValue.tipo = tipo;
            inValue.nroTotalPag = nroTotalPag;
            inValue.nroPagRef = nroPagRef;
            inValue.pagina = pagina;
            pide_api.ServiceReference.verAsientoResponse retVal = ((pide_api.ServiceReference.PIDEWSService)(this)).verAsiento(inValue);
            return retVal.img;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.ServiceReference.verAsientoResponse> pide_api.ServiceReference.PIDEWSService.verAsientoAsync(pide_api.ServiceReference.verAsientoRequest request) {
            return base.Channel.verAsientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.verAsientoResponse> verAsientoAsync(long transaccion, long idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            pide_api.ServiceReference.verAsientoRequest inValue = new pide_api.ServiceReference.verAsientoRequest();
            inValue.transaccion = transaccion;
            inValue.idImg = idImg;
            inValue.tipo = tipo;
            inValue.nroTotalPag = nroTotalPag;
            inValue.nroPagRef = nroPagRef;
            inValue.pagina = pagina;
            return ((pide_api.ServiceReference.PIDEWSService)(this)).verAsientoAsync(inValue);
        }
        
        public pide_api.ServiceReference.respuestaVehiculoBean verDetalleRPV(string zona, string oficina, string placa) {
            return base.Channel.verDetalleRPV(zona, oficina, placa);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.respuestaVehiculoBean> verDetalleRPVAsync(string zona, string oficina, string placa) {
            return base.Channel.verDetalleRPVAsync(zona, oficina, placa);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.ServiceReference.buscarPJRazonSocialResponse pide_api.ServiceReference.PIDEWSService.buscarPJRazonSocial(pide_api.ServiceReference.buscarPJRazonSocialRequest request) {
            return base.Channel.buscarPJRazonSocial(request);
        }
        
        public pide_api.ServiceReference.datosPJBean[] buscarPJRazonSocial(string razonSocial) {
            pide_api.ServiceReference.buscarPJRazonSocialRequest inValue = new pide_api.ServiceReference.buscarPJRazonSocialRequest();
            inValue.razonSocial = razonSocial;
            pide_api.ServiceReference.buscarPJRazonSocialResponse retVal = ((pide_api.ServiceReference.PIDEWSService)(this)).buscarPJRazonSocial(inValue);
            return retVal.personaJuridica;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.ServiceReference.buscarPJRazonSocialResponse> pide_api.ServiceReference.PIDEWSService.buscarPJRazonSocialAsync(pide_api.ServiceReference.buscarPJRazonSocialRequest request) {
            return base.Channel.buscarPJRazonSocialAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.buscarPJRazonSocialResponse> buscarPJRazonSocialAsync(string razonSocial) {
            pide_api.ServiceReference.buscarPJRazonSocialRequest inValue = new pide_api.ServiceReference.buscarPJRazonSocialRequest();
            inValue.razonSocial = razonSocial;
            return ((pide_api.ServiceReference.PIDEWSService)(this)).buscarPJRazonSocialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pide_api.ServiceReference.getOficinasResponse pide_api.ServiceReference.PIDEWSService.getOficinas(pide_api.ServiceReference.getOficinasRequest request) {
            return base.Channel.getOficinas(request);
        }
        
        public pide_api.ServiceReference.oficinaRegistralBean[] getOficinas() {
            pide_api.ServiceReference.getOficinasRequest inValue = new pide_api.ServiceReference.getOficinasRequest();
            pide_api.ServiceReference.getOficinasResponse retVal = ((pide_api.ServiceReference.PIDEWSService)(this)).getOficinas(inValue);
            return retVal.oficina;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pide_api.ServiceReference.getOficinasResponse> pide_api.ServiceReference.PIDEWSService.getOficinasAsync(pide_api.ServiceReference.getOficinasRequest request) {
            return base.Channel.getOficinasAsync(request);
        }
        
        public System.Threading.Tasks.Task<pide_api.ServiceReference.getOficinasResponse> getOficinasAsync() {
            pide_api.ServiceReference.getOficinasRequest inValue = new pide_api.ServiceReference.getOficinasRequest();
            return ((pide_api.ServiceReference.PIDEWSService)(this)).getOficinasAsync(inValue);
        }
    }
}
